export enum ErrorCode {
  EMAIL_ALREADY_TAKEN = "EMAIL_ALREADY_TAKEN",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  INVALID_QUANTITY = "INVALID_QUANTITY",
  SKU_NOT_FOUND = "SKU_NOT_FOUND",
  CART_ITEM_NOT_FOUND = "CART_ITEM_NOT_FOUND",
  CART_QUANTITY_LIMIT_EXCEED = "CART_QUANTITY_LIMIT_EXCEED",
}
